{ config, ... }:
let
  theme = config.omanix.activeTheme;
  c = theme.colors;
in
{
  programs.btop = {
    enable = true;

    settings = {
      color_theme = "omanix";
      theme_background = false;
      vim_keys = true;
    };
  };

  xdg.configFile."btop/themes/omanix.theme".text = ''
    # Theme: ${theme.meta.name} (generated by Omanix)

    # Main background
    theme[main_bg]="${c.background}"

    # Main text color
    theme[main_fg]="${c.foreground}"

    # Title color for boxes
    theme[title]="${c.foreground}"

    # Highlight color for keyboard shortcuts
    theme[hi_fg]="${c.accent}"

    # Background color of selected item in processes box
    theme[selected_bg]="${c.color8}"

    # Foreground color of selected item in processes box
    theme[selected_fg]="${c.accent}"

    # Color of inactive/disabled text
    theme[inactive_fg]="${c.color8}"

    # Color of text appearing on top of graphs
    theme[graph_text]="${c.foreground}"

    # Background color of the percentage meters
    theme[meter_bg]="${c.color8}"

    # Misc colors for processes box including mini cpu graphs, ## ## details memory graph and details status text
    theme[proc_misc]="${c.accent}"

    # CPU box outline color
    theme[cpu_box]="${c.accent}"

    # Memory/disks box outline color
    theme[mem_box]="${c.accent}"

    # Net box outline color
    theme[net_box]="${c.accent}"

    # Processes box outline color
    theme[proc_box]="${c.accent}"

    # Box divider line and target line color
    theme[div_line]="${c.color8}"

    # Temperature graph colors
    theme[temp_start]="${c.color2}"
    theme[temp_mid]="${c.color3}"
    theme[temp_end]="${c.color1}"

    # CPU graph colors
    theme[cpu_start]="${c.accent}"
    theme[cpu_mid]="${c.color5}"
    theme[cpu_end]="${c.color1}"

    # Mem/Disk free meter
    theme[free_start]="${c.color2}"
    theme[free_mid]="${c.color2}"
    theme[free_end]="${c.color2}"

    # Mem/Disk cached meter
    theme[cached_start]="${c.color4}"
    theme[cached_mid]="${c.color4}"
    theme[cached_end]="${c.color4}"

    # Mem/Disk available meter
    theme[available_start]="${c.color3}"
    theme[available_mid]="${c.color3}"
    theme[available_end]="${c.color3}"

    # Mem/Disk used meter
    theme[used_start]="${c.color5}"
    theme[used_mid]="${c.color1}"
    theme[used_end]="${c.color1}"

    # Download graph colors
    theme[download_start]="${c.accent}"
    theme[download_mid]="${c.accent}"
    theme[download_end]="${c.color5}"

    # Upload graph colors
    theme[upload_start]="${c.color2}"
    theme[upload_mid]="${c.color2}"
    theme[upload_end]="${c.color3}"

    # Process box color gradient for threads, mem and cpu usage
    theme[process_start]="${c.accent}"
    theme[process_mid]="${c.color5}"
    theme[process_end]="${c.color1}"
  '';
}
