{ ... }:
{
  imports = [
    ./theme
    ./scripts
    ./core/fonts.nix
    ./core/gtk.nix
    ./core/shell.nix
    ./core/git.nix
    ./core/languages.nix
    ./apps/firefox.nix
    ./apps/jetbrains.nix
    ./apps/neovim.nix
    ./apps/spotatui.nix
    ./desktop/hyprland/autostart.nix
    ./desktop/hyprland/envs.nix
    ./desktop/hyprland/visuals.nix
    ./desktop/hyprland/bindings.nix
    ./desktop/hyprland/input.nix
    ./desktop/hyprland/rules.nix
    ./desktop/hyprland/monitors.nix
    ./desktop/hyprpaper.nix
    ./desktop/hypridle.nix
    ./desktop/hyprlock.nix
    ./ui/waybar.nix
    ./ui/elephant.nix
    ./ui/walker.nix
    ./ui/hidden-apps.nix
    ./ui/swayosd.nix
    ./terminal/ghostty.nix
    ./core/bat.nix
  ];
}
